name = "ARCOMM Patches"
author = "ARCOMM"
prefix = "arc_ptc"
mainprefix = "z"

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
]
